const UPDATE_CITY_COORDS_REQUEST = "UPDATE_CITY_COORDS_REQUEST";
const UPDATE_CITY_COORDS_SUCCESS = "UPDATE_CITY_COORDS_SUCCESS";
const UPDATE_CITY_COORDS_FAILURE = "UPDATE_CITY_COORDS_FAILURE";

const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
const CURRENT_WEATHER_SUCCESS = "CURRENT_WEATHER_SUCCESS";
const CURRENT_WEATHER_FAILURE = "CURRENT_WEATHER_FAILURE";

export default {
    UPDATE_CITY_COORDS_REQUEST,
    UPDATE_CITY_COORDS_SUCCESS,
    UPDATE_CITY_COORDS_FAILURE,
    CURRENT_WEATHER_REQUEST,
    CURRENT_WEATHER_SUCCESS,
    CURRENT_WEATHER_FAILURE
}